import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  FaPlus,
  FaEdit,
  FaInbox,
  FaStar,
  FaClock,
  FaPaperPlane,
  FaFirstdraft,
  FaFilter,
  FaArrowAltCircleRight,
  FaTag,
  FaTrash,
  FaTasks,
  FaUsers,
  FaUser,
  FaUserCog,
  FaUserCircle,
  FaArrowRight,
  FaArrowLeft,
  FaArrowUp,
  FaArrowDown,
  FaKeyboard,
  FaExclamationCircle,
  FaExclamationTriangle,
  FaExclamation,
  FaAppStore,
  FaQuestionCircle,
  FaPlusSquare,
  FaMinusSquare,
  FaCaretDown,
  FaCaretUp,
  FaCaretRight,
  FaCaretLeft,
  FaArchive,
  FaAddressBook,
  FaCalendar,
  FaLightbulb,
  FaPrint,
  FaSmile,
  FaReply,
  FaReplyAll,
  FaCheck,
  FaForward,
  FaBell,
  FaBars,
  FaEnvelope,
  FaSearch,
  FaFileArchive,
  
} from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
